### Multi-class segmentation with mmsegmentation🥳

#### Related dataset & notebook:
* [Creat multi-class dataset  (notebook)](https://www.kaggle.com/code/w3579628328/6-classes-dataset-for-mmsegmentation)
* [256x256  (dataset)](https://www.kaggle.com/datasets/w3579628328/mmsegmentation256x256)
* [512x512  (dataset)](https://www.kaggle.com/datasets/w3579628328/mmsegmentation512x512)

#### Related baseline for training:
* [Binary sementation with mmsegmentation](https://www.kaggle.com/code/w3579628328/mmsegmentation-trainning)

#### Look forward to your upvote again🤗🤗🤗

In [13]:
!gdown 1OC7HRDEp99HiMdVD8p1P1HWDcl3My0eX

Downloading...
From: https://drive.google.com/uc?id=1OC7HRDEp99HiMdVD8p1P1HWDcl3My0eX
To: /content/mmsegmentation/DeepLabUnet.zip
100% 3.62k/3.62k [00:00<00:00, 7.62MB/s]


In [14]:
!unzip /content/mmsegmentation/DeepLabUnet.zip

Archive:  /content/mmsegmentation/DeepLabUnet.zip
   creating: Deep_Unet/
  inflating: Deep_Unet/schedule_40k.py  
  inflating: Deep_Unet/deeplabv3_unet_s5-d16.py  
  inflating: Deep_Unet/default_runtime.py  
  inflating: Deep_Unet/customdataset.py  
  inflating: Deep_Unet/deeplabv3_unet_s5-d16_ce-1.0-dice-3.0_256x256_40k_hrf.py  
  inflating: Deep_Unet/deeplabv3_unet_s5-d16_256x256_40k_hrf.py  


In [15]:
!gdown 1-1M56Jq0-YaFeFM6bsOOr1IhfOQznqZW

Downloading...
From: https://drive.google.com/uc?id=1-1M56Jq0-YaFeFM6bsOOr1IhfOQznqZW
To: /content/mmsegmentation/mmsegmentation.zip
100% 658M/658M [00:11<00:00, 59.1MB/s]


In [16]:
!unzip /content/mmsegmentation/mmsegmentation.zip

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
  inflating: mmsegmentation/mmseg_data/train/2874_0008.png  
  inflating: mmsegmentation/mmseg_data/train/5583_0005.png  
  inflating: mmsegmentation/mmseg_data/train/25689_0003.png  
  inflating: mmsegmentation/mmseg_data/train/10044_0004.png  
  inflating: mmsegmentation/mmseg_data/train/14407_0007.png  
  inflating: mmsegmentation/mmseg_data/train/8638_0004.png  
  inflating: mmsegmentation/mmseg_data/train/5552_0001.png  
  inflating: mmsegmentation/mmseg_data/train/19997_0006.png  
  inflating: mmsegmentation/mmseg_data/train/5583_0008.png  
  inflating: mmsegmentation/mmseg_data/train/2279_0005.png  
  inflating: mmsegmentation/mmseg_data/train/19084_0008.png  
  inflating: mmsegmentation/mmseg_data/train/29307_0005.png  
  inflating: mmsegmentation/mmseg_data/train/27232_0001.png  
  inflating: mmsegmentation/mmseg_data/train/21112_0003.png  
  inflating: mmsegmentation/mmseg_data/train/7970_0001.png  
  inflating: mmsegmentation/mmseg_data/tr

In [1]:
## MMSegmentation Framework을 사용하기 위한 Install
# Install PyTorch
!pip install torch==1.12.0 torchvision --extra-index-url https://download.pytorch.org/whl/cu113
# Install MMCV
!pip install openmim
!mim install mmcv-full==1.6.0
# git clone
!git clone https://github.com/open-mmlab/mmsegmentation.git 
%cd mmsegmentation
!pip install -e .

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/, https://download.pytorch.org/whl/cu113
     |██████████████▌                 | 834.1 MB 1.2 MB/s eta 0:13:35tcmalloc: large alloc 1147494400 bytes == 0x38c96000 @  0x7f836109c615 0x592b76 0x4df71e 0x59afff 0x515655 0x549576 0x593fce 0x548ae9 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x598e3b 0x511f68 0x598e3b 0x511f68 0x598e3b 0x511f68 0x4bc98a 0x532e76 0x594b72 0x515600 0x549576 0x593fce 0x548ae9 0x5127f1 0x549576 0x593fce 0x5118f8 0x593dd7
     |██████████████████▍             | 1055.7 MB 1.2 MB/s eta 0:11:17tcmalloc: large alloc 1434370048 bytes == 0x7d2ec000 @  0x7f836109c615 0x592b76 0x4df71e 0x59afff 0x515655 0x549576 0x593fce 0x548ae9 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x598e3b 0x511f68 0x598e3b 0x511f68 0x598e3b 0x511f68 0x4bc98a 0x532e76 0x594b72 0x515600 0x549576 0x593fce 0x548ae9 0x5127f1 0x549576 0x593fce 0x5118f8 0x593dd7
     |███████████████████████▎        | 

In [2]:
!pip install -q --upgrade wandb

     |████████████████████████████████| 1.8 MB 5.1 MB/s 
     |████████████████████████████████| 181 kB 76.6 MB/s 
     |████████████████████████████████| 157 kB 70.9 MB/s 
     |████████████████████████████████| 63 kB 1.8 MB/s 
     |████████████████████████████████| 157 kB 74.6 MB/s 
     |████████████████████████████████| 157 kB 84.2 MB/s 
     |████████████████████████████████| 157 kB 104.6 MB/s 
     |████████████████████████████████| 157 kB 83.6 MB/s 
     |████████████████████████████████| 156 kB 81.6 MB/s 


In [5]:
import wandb
wandb.login()

True

In [6]:
!mkdir -p ./mmseg_data/splits

In [7]:
## load dataset
!gdown 1787fZejOECLSAWpMg8fDwDgWSz6gTusT # multi class 256x256
!unzip /content/mmsegmentation/Multi_256x256_MMSeg.zip

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
  inflating: masks/164_0005.png      
  inflating: masks/164_0006.png      
  inflating: masks/164_0007.png      
  inflating: masks/164_0008.png      
  inflating: masks/16564_0001.png    
  inflating: masks/16564_0002.png    
  inflating: masks/16564_0003.png    
  inflating: masks/16564_0004.png    
  inflating: masks/16564_0005.png    
  inflating: masks/16564_0007.png    
  inflating: masks/16564_0008.png    
  inflating: masks/16609_0000.png    
  inflating: masks/16609_0001.png    
  inflating: masks/16609_0002.png    
  inflating: masks/16609_0003.png    
  inflating: masks/16609_0004.png    
  inflating: masks/16609_0005.png    
  inflating: masks/16609_0006.png    
  inflating: masks/16609_0007.png    
  inflating: masks/16609_0008.png    
  inflating: masks/16659_0000.png    
  inflating: masks/16659_0001.png    
  inflating: masks/16659_0002.png    
  inflating: masks/16659_0003.png    
  inflating: masks/16659_0004.png    
  inflating: m

In [8]:
# !mkdir /content/mmsegmentation/mmseg_data
!mv /content/mmsegmentation/train /content/mmsegmentation/mmseg_data
!mv /content/mmsegmentation/masks /content/mmsegmentation/mmseg_data

##### Start with 256x256 data

In [9]:
!mkdir ./mmseg_data/splits

mkdir: cannot create directory ‘./mmseg_data/splits’: File exists


In [10]:
from glob import glob
import numpy as np
import cv2
import os
from sklearn.model_selection import StratifiedKFold

Fold = 10
all_mask_files = glob("./mmseg_data/masks/*")
masks = []
num_mask = np.zeros((6,Fold))

for i in range(len(all_mask_files)):
    mask = cv2.imread(all_mask_files[i])
    masks.append(mask.max())

## train_valid_split, KFold : 교차검증
split = list(StratifiedKFold(n_splits=Fold, shuffle=True, random_state=2022).split(all_mask_files, masks))
for fold, (train_idx, valid_idx) in enumerate(split):
    for i in valid_idx:
        num_mask[masks[i]]+=1
    with open(f"./mmseg_data/splits/fold_{fold}.txt", "w") as f:
        for idx in train_idx:
            f.write(os.path.basename(all_mask_files[idx])[:-4] + "\n")
    with open(f"./mmseg_data/splits/valid_{fold}.txt", "w") as f:
        for idx in valid_idx:
            f.write(os.path.basename(all_mask_files[idx])[:-4] + "\n")
print(num_mask)

[[947. 947. 947. 947. 947. 947. 947. 947. 947. 947.]
 [396. 396. 396. 396. 396. 396. 396. 396. 396. 396.]
 [559. 559. 559. 559. 559. 559. 559. 559. 559. 559.]
 [435. 435. 435. 435. 435. 435. 435. 435. 435. 435.]
 [282. 282. 282. 282. 282. 282. 282. 282. 282. 282.]
 [172. 172. 172. 172. 172. 172. 172. 172. 172. 172.]]


* Larger backbone and more iters may lead to better score!

In [ ]:
# %%bash

# cat <<EOT >> /kaggle/working/config.py
## config.py (= _base_.py)

In [11]:
%%bash

cat <<EOT >> /content/mmsegmentation/config.py # 빈 config.py 생성해주기

## model setting
norm_cfg = dict(type='SyncBN', requires_grad=True)
model = dict(
    type='EncoderDecoder',
    pretrained=None,
    backbone=dict(
        type='UNet',
        in_channels=3,
        base_channels=64,
        num_stages=5,
        strides=(1, 1, 1, 1, 1),
        enc_num_convs=(2, 2, 2, 2, 2),
        dec_num_convs=(2, 2, 2, 2),
        downsamples=(True, True, True, True),
        enc_dilations=(1, 1, 1, 1, 1),
        dec_dilations=(1, 1, 1, 1),
        with_cp=False,
        conv_cfg=None,
        norm_cfg=norm_cfg,
        act_cfg=dict(type='ReLU'),
        upsample_cfg=dict(type='InterpConv'),
        norm_eval=False),
    decode_head=dict(
        type='ASPPHead',
        in_channels=64,
        in_index=4,
        channels=16,
        dilations=(1, 12, 24, 36),
        dropout_ratio=0.1,
        num_classes=6,
        norm_cfg=norm_cfg,
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
    auxiliary_head=dict(
        type='FCNHead',
        in_channels=128,
        in_index=3,
        channels=64,
        num_convs=1,
        concat_input=False,
        dropout_ratio=0.1,
        num_classes=6,
        norm_cfg=norm_cfg,
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.4)),
    train_cfg=dict(),
    test_cfg=dict(mode='slide', crop_size=256, stride=170))

## dataset settings
dataset_type = 'CustomDataset'
data_root = '/content/mmsegmentation/mmseg_data/'
classes = ['background', 'kidney', 'prostate', 'largeintestine', 'spleen', 'lung']
palette = [[0,0,0], [255,0,0], [0,255,0], [0,0,255], [255,255,0], [255,0,255]]
img_norm_cfg = dict(mean=[196.869, 190.186, 194.802], std=[63.010, 66.765, 65.745], to_rgb=True)
size = 256

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Resize', img_scale=(size, size), keep_ratio=True),
    dict(type='RandomFlip', prob=0.5, direction='horizontal'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size=(size, size), pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(size, size),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size=(size, size), pad_val=0, seg_pad_val=255),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    samples_per_gpu=8,
    workers_per_gpu=4,
    train=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir='train', # image경로
        ann_dir='masks', # mask.png경로
        img_suffix=".png",
        seg_map_suffix='.png',
        split="splits/fold_0.txt",
        classes=classes,
        palette=palette,
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir='train',
        ann_dir='masks',
        img_suffix=".png",
        seg_map_suffix='.png',
        split="splits/valid_0.txt",
        classes=classes,
        palette=palette,
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        data_root=data_root,
        test_mode=True,
        img_dir='train',
        ann_dir='masks',
        img_suffix=".png",
        seg_map_suffix='.png',
        classes=classes,
        palette=palette,
        pipeline=test_pipeline))

# yapf:disable
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook', by_epoch=False),
        dict(type='WandbLoggerHook', interval=50, # connect Wandb
             init_kwargs=dict(
                 project='HuBMAP',
                 entity='yoonsomi',
                 name='unet'),
             )
    ])
# yapf:enable
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
cudnn_benchmark = True

total_iters = 5000
# optimizer
optimizer = dict(type='AdamW', lr=1e-3, betas=(0.9, 0.999), weight_decay=0.05)
optimizer_config = dict(type='Fp16OptimizerHook', loss_scale='dynamic')
# learning policy
lr_config = dict(policy='poly',
                 warmup='linear',
                 warmup_iters=500,
                 warmup_ratio=1e-6,
                 power=1.0, min_lr=0.0, by_epoch=False)
# runtime settings
find_unused_parameters = True
runner = dict(type = 'IterBasedRunner', max_iters = total_iters)
checkpoint_config = dict(by_epoch=False, interval=-1, save_optimizer=False)
evaluation = dict(by_epoch=False, interval=500, metric='mDice', pre_eval=True)
fp16 = dict()
work_dir = './baseline'
EOT

#### Train with api

In [12]:
!python /content/mmsegmentation/tools/train.py /content/mmsegmentation/config.py

2022-08-16 14:38:29,238 - mmseg - INFO - Multi-processing start method is `None`
2022-08-16 14:38:29,244 - mmseg - INFO - OpenCV num_threads is `4
2022-08-16 14:38:29,314 - mmseg - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.7.13 (default, Apr 24 2022, 01:04:09) [GCC 7.5.0]
CUDA available: True
GPU 0: Tesla T4
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.1, V11.1.105
GCC: x86_64-linux-gnu-gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.12.0+cu113
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC arc

In [ ]:
\!gdown 1VnXyPKFiRL5Cvmw3UXLIK6Id93vjgKW5

In [ ]:
%cd /content/mmsegmentation

In [ ]:
!unzip /content/mmsegmentation/hubmap-organ-segmentation.zip

#### Inference

In [ ]:
import cv2
import numpy as np
import pandas as pd
import os
from glob import glob
from tqdm.notebook import tqdm
import sys
import gc
sys.path.append('./mmsegmentation-master')
from mmseg.apis import init_segmentor, inference_segmentor
from mmcv.utils import config

In [ ]:
configs = [
    '/content/mmsegmentation/config/py',
]
ckpts = [
    '/content/mmsegmentation/CKPTS', # ckpts.pth(weight) 경로
]

DATA = '/content/mmsegmentation/DATA' # test img 경로
df_sample = pd.read_csv('').set_index('id') # sample_submission.csv(?) 경로

models = []
for idx,(cfg, ckpt) in enumerate(zip(configs, ckpts)):
    cfg = config.Config.fromfile(cfg)
    model = init_segmentor(cfg, ckpt, device='cuda:0')
    models.append(model)

In [ ]:
### mask -> rle
def rle_encode_less_memory(img):
    pixels = img.T.flatten()
    pixels[0] = 0
    pixels[-1] = 0
    runs = np.where(pixels[1:] != pixels[:-1])[0] + 2
    runs[1::2] -= runs[::2]
    return ' '.join(str(x) for x in runs)

In [ ]:
'''
To ensemble models, you need to do some modifications with 
"../input/mmsegm/mmsegmentation-master/mmseg/models/segmentors/encoder_decoder.py"
'''
names,preds = [],[]
imgs, pd_mks = [],[]
debug = len(df_sample)<2
for idx,row in tqdm(df_sample.iterrows(),total=len(df_sample)):
    img  = cv2.imread(os.path.join(DATA,str(idx)+'.tiff'))
    im_  = img/img.max()
    pred = inference_segmentor(models[0], im_)[0]
    pred = (pred>0).astype(np.uint8)
    rle = rle_encode_less_memory(pred)
    names.append(str(idx))
    preds.append(rle)
    if debug:
        imgs.append(img)
        pd_mks.append(pred)
    del img, pred, rle, idx, row
    gc.collect()

In [ ]:
if debug:
    import matplotlib.pyplot as plt
    for img, mask in zip(imgs, pd_mks):
        plt.figure(figsize=(12, 7))
        plt.subplot(1, 3, 1); plt.imshow(img); plt.axis('OFF'); plt.title('image')
        plt.subplot(1, 3, 2); plt.imshow(mask*255); plt.axis('OFF'); plt.title('mask')
        plt.subplot(1, 3, 3); plt.imshow(img); plt.imshow(mask*255, alpha=0.4); plt.axis('OFF'); plt.title('overlay')
        plt.tight_layout()
        plt.show()